name: CI Pipeline

on:
  push:
    branches:
      - main  # Altere para o nome da sua branch principal
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel  # Instala setuptools e wheel
        pip install -r requirements.txt

    - name: Build Distribution
      run: |
        python setup.py sdist bdist_wheel

    - name: Check if dist directory exists
      run: |
        if [ -d "dist" ]; then
          echo "Directory 'dist' exists."
        else
          echo "Directory 'dist' does not exist."
          exit 1
        fi

    - name: Run Tests
      run: |
        pip install pytest
        pytest tests/
